---
- hosts: gitolite-server
  user: root
  tasks:
    - name: "Install gitolite"
      action: "apt name=gitolite state=installed"
    - name: "Create gitolite user"
      action: "user name=gitolite createhome=yes"
    - name: "Add initial gitolite rc file"
      action: "copy dest=$gitolite_home/.gitolite.rc src=templates/gitolite.rc mode=0644 owner=gitolite group=gitolite"
    - name: "Create ssh directory"
      action: "file dest=$gitolite_home/.ssh state=directory mode=0700 owner=gitolite group=gitolite"
    - name: "Push public gitolite key"
      action: "copy dest=$gitolite_home/.ssh/gitolite-ssh-key.pub src=$gitolite_public_key owner=gitolite group=gitolite mode=0660"
    - name: "Final gitolite setup"
      action: "shell sudo -Hu gitolite /bin/bash -c '(cd $gitolite_home && gl-setup $gitolite_home/.ssh/gitolite-ssh-key.pub)'"
  vars_files:
    - 'vars/default.yml'
